### ISSUE TITLE
Relative vs. Absolute href on journal pages

### ISSUE THREAD

**Issue by pbulsink** [ContentMine/quickscrape#28]
I'm trying to write scrapers for ACS and Nature, and they use relative links in their pages.  The scraper doesn't appear to follow these relative links.

eg: for http://pubs.acs.org/doi/abstract/10.1021/ja409271s the fulltext pdf link is `<a title="Download the PDF Full Text" href="/doi/pdf/10.1021/ja409271s">`, this is not followed by the json:

```json
...
    "fulltext_pdf": {
      "selector": "//a[@title='Download the PDF Full Text']",
      "attribute": "href",
      "download": true
    },
...
```

**Comment by Blahah** [comment]
Relative link resolution is now included
