### ISSUE TITLE
Is there a scraper for Elsevier

### ISSUE THREAD

**Issue by petermr** [ContentMine/quickscrape#49]
Did you create a scraper for Elsevier (I know the lazy load Javascript needing addressing)? I seemed to remember you created at least a prototype. We shall need one.

**Comment by Blahah** [comment]
This should be an issue on http://github.com/contentmine/journal-scrapers.

There is a sciencedirect scraper in the `non-open` branch of that repo: https://github.com/ContentMine/journal-scrapers/blob/non-open/scrapers/science_direct.json

**Comment by petermr** [comment]
On Sat, Jun 13, 2015 at 9:07 PM, Richard Smith-Unna <
notifications@github.com> wrote:

> This should be an issue on http://github.com/contentmine/journal-scrapers
> <https://github.com/contentmine/journal-scrapers>.
>
> There is a sciencedirect scraper in the non-open branch of that repo:
> https://github.com/ContentMine/journal-scrapers/blob/non-open/scrapers/science_direct.json
>

does "non-open" mean that the papers are non-(Open Access) or that the
scraper directory itself is not public - I'll assume the former.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ContentMine/quickscrape/issues/49#issuecomment-111743979>
> .
>



-- 
Peter Murray-Rust
Reader in Molecular Informatics
Unilever Centre, Dep. Of Chemistry
University of Cambridge
CB2 1EW, UK
+44-1223-763069

**Comment by Blahah** [comment]
Yes, the former.
