### ISSUE TITLE
Scraper list option?

### ISSUE THREAD

**Issue by chartgerink** [ContentMine/quickscrape#58]
Currently quickscrape supports the feeding in of a urllist, but not a scraper list. This results in the fact that the urllist thus needs to contain links for the same publisher only. Would it be possible to implement a scraper list argument as well, such that a urllist of various publishers can be used as input with the appropriate scrapers? I figure this would increase usability and decrease load to the server, because requests can be randomly varied over publisher/server.

My apologies if I am missing something very obvious which already implemented this.

**Comment by Blahah** [comment]
this is already possible - use the `--scraperdir` argument to give the path to a directory full of scraperJSON scrapers.

**Comment by chartgerink** [comment]
OK thanks, I misinterpreted what that argument did then! My apologies.

**Comment by Blahah** [comment]
Could we make the help text clearer do you think?

**Comment by chartgerink** [comment]
Maybe add something along the lines of "to which the supplied URLs are
matched"?

On Wednesday, September 30, 2015, Richard Smith-Unna <
notifications@github.com

**Comment by Blahah** [comment]
Thanks, I've created an issue to do a review of the command line.

> My apologies.

No need to apologise! Is a user is confused by software, it is invariably the fault of the developers. It's our job to make it perfectly clear. Thanks for reporting :)
