### ISSUE TITLE
v0.4.7 breaks scraping in Windows

### ISSUE THREAD

**Issue by chartgerink** [ContentMine/quickscrape#60]
Hi Richard,

I just updated to v0.4.7 but this breaks scraping of files because of a misspecification in scraper paths. It seems to get confounded with the output path (see attached). After downgrading to v0.4.6 it works again. 
![capture](https://cloud.githubusercontent.com/assets/2946344/10455205/3da5f0a0-71ba-11e5-9aec-16eaede086eb.PNG)

**Comment by Blahah** [comment]
Ah, sorry about this. I don't have a windows machine to test on, but will see if I can figure it out.

**Comment by chartgerink** [comment]
Hm I just tried this on Ubuntu and I get the same error. I have the most up-to-date version of node and updated quickscrape to be sure, but somehow the folder name for the output is seen as input for the journal-scraper location (pwd is correct parent folder, `/media/chjh/contentmine` in the case below). 

Does quickscrape@0.4.7 properly work for you? If so, I wonder what goes wrong on my end.

![screenshot from 2015-10-28 09 01 01](https://cloud.githubusercontent.com/assets/2946344/10782679/98627cf4-7d52-11e5-959c-648b68c8c092.png)
