### ISSUE TITLE
links with many special characters not properly scraped

### ISSUE THREAD

**Issue by chartgerink** [ContentMine/quickscrape#65]
I am trying to scrape some links from wiley, but quickscrape only reads the link partly. An example is `http://onlinelibrary.wiley.com/doi/10.1002/(SICI)1097-0193(2000)9:1<1::AID-HBM1>3.0.CO;2-%23/full` which it only reads as, for instance, `http://onlinelibrary.wiley.com/doi/10.1002/(SICI)1097-0193(`.

This of course does not render properly, but any idea how to solve this either from my end or the program's end? I tried encapsulating the link in single quotes, but then quickscrape does not even recognize the link.

(I will try and learn node soon so I can start proposing solutions to all the issues I am raising, Richard. My apologies!)

**Comment by petermr** [comment]
Thanks very much Chris and we are delighted to have your contributions. I will hopefully accompany you on your journey of learning `Node.js` - I need to understand the toolchain. I can't solve your problem, but I am guessing it will be a regex or a URL-encoding somewhere which can't manage this (awful) URL. I wonder if there is an alternative. Can you show where the URL came from and also the URL you would get by browsing the journal site?

**Comment by petermr** [comment]
Actually I have looked at the site and these seem to be the actual URLs. I imagine it maps onto some database query.

**Comment by Blahah** [comment]
That is the ugliest URL I have ever seen! I thought we had resolved these kinds of issues before with our encoding ritual, but clearly not. I'll dig into it ASAP, and @petermr I'll write a blog post about debugging this one to help you get into it.

**Comment by chartgerink** [comment]
Any updates on this? I have been able to pinpoint the problem to the `%23` in the link, because the others do work with all the special characters in place.

**Comment by chartgerink** [comment]
Apparently it did work, but Terminal was not recognizing the link properly.
