### ISSUE TITLE
scraper directory is wrong

### ISSUE THREAD

**Issue by skasberger** [ContentMine/quickscrape#67]
the scraper directory is concatened wrong. it adds the output directory between the working directory and the scraper folder. 

node 5.0.0
quickscrape 0.4.7

i this case:
```
info: - Scraper: /my-data/io/quickscrape/peerj-384/journal-scrapers/scrapers/peerj.json
``` 
but should be 
```
info: - Scraper: /my-data/io/quickscrape/journal-scrapers/scrapers/peerj.json
``` 
![issue](https://cloud.githubusercontent.com/assets/1374253/11326719/1231f988-9171-11e5-8e0a-89977c54b6ae.png)

**Comment by Blahah** [comment]
Thanks - this is what was causing #60 I think. Must have been a typo in the last release.
