### ISSUE TITLE
Remove requirement for `-o` with `-n`

### ISSUE THREAD

**Issue by petermr** [ContentMine/quickscrape#73]
If `-n` is used there is no need for `-o` and it's extra typing or confusion.
e.g.
```
getpapers -q aardvark -n
```
should be enough

**Comment by blahah** [comment]
good point!

**Comment by tarrow** [comment]
Issue moved to [ContentMine/getpapers #90](https://github.com/ContentMine/getpapers/issues/90) via [**ZenHub.io**](https://www.zenhub.io/)
