### ISSUE TITLE
High severity vulnerability affecting this repo

### ISSUE THREAD

**Issue by benmag1** [ContentMine/quickscrape#94]
Hi there, 

We noticed that your repo has a high severity vulnerability: 
* [ReDoS via long string of semicolons](https://snyk.io/vuln/npm:tough-cookie:20160722?utm_source=gh_issue)
* Affected package: tough-cookie<=2.2.2 

[Here is the test report for this repo](https://snyk.io/test/github/ContentMine/quickscrape?utm_source=gh_issue). 
If you’d like to fix this vulnerability, Snyk lets you generate a pull request that recommends the best upgrade path - there’s a link to fix this vulnerability on the test report. 

Stay secure :-)

Ben from the Snyk team

**Comment by tarrow** [comment]
Hi Ben,

Thanks for flagging this up; we have been a little slow on providing
updates to thresher and it's increasingly ancient dependencies.

Cheers,
Tom

**Comment by blahah** [comment]
This vuln really doesn't matter much for quickscrape. It's an issue where malformed user input could crash the program. It's a problem for server software, daemons, stuff like that. For a simple CLI it doesn't matter.
