### ISSUE TITLE
Quickscrape not scraping through my list of 1000 URLs

### ISSUE THREAD

**Issue by alexmaina** [ContentMine/quickscrape#98]
I have a list of 1000 Urls. Whenever i run quickscrape it only scrapes 1 url and then hangs. Is it an issue of internet bandwidth or is it the firewall? I live in Kenya.

**Comment by rossmounce** [comment]
Hi @alexmaina could you post both the input and the output, your operating system (Win/OSX/Linux), as well as the version of quickscrape you're using? You can get the version of quickscrape with:
```
quickscrape -V
```

**Comment by alexmaina** [comment]
Hi @rossmounce 

This is the input
`quickscrape -r /home/alex/Kenya/eupmc_fulltext_html_urls.txt -d /home/alex/journal-scrapers/scrapers/ -o /home/alex/Kenya/scraped_results`

After downloading a few fulltexts, the system hangs giving this output

info: [scraper]. URL rendered. http://europepmc.org/articles/PMC5223685.
info: [scraper]. download started. fulltext.html.
info: [scraper]. download started. fulltext.pdf.
info: URL processed: captured 10/10 elements (0 captures failed)
http://europepmc.org/articles/PMC5095351


my version of quickscrape is 0.4.7

**Comment by rossmounce** [comment]
Doesn't `quickscrape` require one to set a journal-specific scraper? Perhaps this could be the problem?

I am presuming that `eupmc_fulltext_html_urls.txt` contains article URLs from a variety of journals/publishers.

Furthermore, I checked http://europepmc.org/articles/PMC5223685 and found it to be from BMJ Open which is an entirely open access journal. For articles at entirely open access journals you can use `getpapers` to download them via the EuropePMC API. One only needs to use `quickscrape` for articles at subscription journals.

Does that make sense?

**Comment by rossmounce** [comment]
As a workaround you could also try passing each URL to quickscrape individually with a simple while read loop:

```
#!/usr/bin/env bash
while read url
do
  quickscrape --url $url -d /home/alex/journal-scrapers/scrapers/ -o /home/alex/Kenya/scraped_results
done < eupmc_fulltext_html_urls.txt
```

**Comment by alexmaina** [comment]
Yes. Makes a lot of sense. I highly suspect it has to do with internet connectivity mainly because each time i run quickscrape i get different results. For instance, after running it today, it has downloaded fulltexts until when it got to this url:

info: processing URL: http://europepmc.org/articles/PMC4947939

This is a Wiley journal and while the journal may not be open access, the article is open access.

**Comment by alexmaina** [comment]
The workaround works well but still not getting me full texts for all the 1000 urls

**Comment by rossmounce** [comment]
Could you give a couple of individual examples of a quickscrape commands including the exact URL, for which you don't get the fulltext?

**Comment by alexmaina** [comment]
I have run this now

```
#!/usr/bin/env bash
while read url
do
  quickscrape --url $url -d /home/alex/journal-scrapers/scrapers/ -o /home/alex/Kenya/scraped_results
done < eupmc_fulltext_html_urls.txt

```
and it stops at this url after downloading 478 out of 1000:

http://europepmc.org/articles/PMC5174162


I then run this command:

`quickscrape -r /home/alex/Kenya/eupmc_fulltext_html_urls.txt -d /home/alex/journal-scrapers/scrapers/ -o /home/alex/Kenya/my_results`

and it stops at this url after downloading 730.


http://europepmc.org/articles/PMC4975461

Another question that is not related to this.....

Does quickscrape and getpapers perform the same function? Or should i first get the metadata using getpapers and then get full-texts using quickscrape? The tutorials seem to suggest the later

**Comment by alexmaina** [comment]
What does quickscrape do that getpapers cannot do? Why should i use quickscrape for my list of PMIDs?

**Comment by blahah** [comment]
for PMIDs there's really no reason to use quickscrape

**Comment by blahah** [comment]
quickscrape is useful for scraping fulltexts when they aren't open access but you have access some other way :)

**Comment by alexmaina** [comment]
Thanks @blahah.

**Comment by tarrow** [comment]
Unfortunately the terms are quite confusing. Quite a few things with PMIDs (i.e. anything in MEDLINE) are not open access and you would need quickscrape and a subscription to get them.

Things with PMCIDs (i.e. things that are in pubmedcentral) are much more likely to be open access (and is this case you can get them with getpapers (or just hit a PMC repository with curl, wget etc..))

**Comment by alexmaina** [comment]
Thanks @tarrow. It is inevitable to limit my corpus to open access articles only.
