### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by itahmid** [ContentMine/quickscrape#99]
Hello,

I just followed the example provided and below are the results. I am new to scraping and web data mining. Could you please look into the issue and help resolve.

quickscrape --url https://peerj.com/articles/384 --scraper journal-scrapers/scrapers/peerj.json --output peerj-384 --outformat bibjson
info: quickscrape 0.4.7 launched with...
info: - URL: https://peerj.com/articles/384
info: - Scraper: /var/www/html/my_scraper/data-test/peerj-384/journal-scrapers/scrapers/peerj.json
info: - Rate limit: 3 per minute
info: - Log level: info
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/var/www/html/my_scraper/data-test/peerj-384/journal-scrapers/scrapers/peerj.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/usr/lib/node_modules/quickscrape/bin/quickscrape.js:138:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by tarrow** [comment]
Hi @itahmid,

It looks to me like the scraper file you have specified with `--scraper journal-scrapers/scrapers/peerj.json` doesn't exist. Can you confirm that it does? Perhaps you cloned the scrapers repository to somewhere else? Please reopen if there is indeed a scraper file at "/var/www/html/my_scraper/data-test/peerj-384/journal-scrapers/scrapers/peerj.json"

P.S. If you have more problems that aren't bugs feel free to join us on our forums at discuss.contentmine.org for more support
